var verbs = {
    "header": ["Infinitiv","Präsens","Präteritum","Perfekt","Beispielsatz"],
    "body": [
        ["abfahren","fährt ab","fuhr ab","ist abgefahren","Der Bus fährt um 09.12 Uhr ab."],
        ["abfliegen","fliegt ab","flog ab","ist abgeflogen","Das Flugzeug ist pünktlich abgeflogen."],
        ["abgeben","gibt ab","gab ab","hat abgegeben","Wir gaben Flaschen und Schirme am Eingang ab."],
        ["abhängen","hängt ab","hing ab","hat abgehangen","Es hängt von der Situation ab, wie schnell die Zeit vergeht. "],
        ["abheben","hebt ab","hob ab","hat abgehoben","Mit einer Kreditkarte können sie weltweit Geld abheben. "],
        ["ablesen","liest ab","las ab","hat abgelesen","Sie hat die Stichworte abgelesen."],
        ["abnehmen","nimmt ab","nahm ab","hat abgenommen","Wir nehmen Ihnen Ihre Sorgen ab."],
        ["abraten","rät ab","riet ab","hat abgeraten","Freunde haben Ihr abgeraten."],
        ["abschließen","schließt ab","schloss ab","hat abgeschlossen","Hast du die Tür abgeschlossen?"],
        ["abziehen","zieht ab","zog ab","ist abgezogen","Er zog mit seiner Beute ab."],
        ["anbieten","bietet an","bot an","hat angeboten","Hast du ihm einen Kaffee angeboten?"],
        ["anfangen","fängt an","fing an","hat angefangen","Eva hat angefangen zu arbeiten."],
        ["angehen","geht an","ging an","ist angegangen","Was ich mache, geht doch keinen etwas an!"],
        ["anhaben","hat an","hatte an","hat angehabt","Was hatten Sie gestern an?"],
        ["ankommen","kommt an","kam an","ist angekommen","Wann bist du angekommen?"],
        ["anlassen","lässt an","ließ an","hat angelassen","Er hat die Schuhe angelassen."],
        ["annehmen","nimmt an","nahm an","hat angenommen","Er hat das Päckchen angenommen. "],
        ["anrufen","ruft an","rief an","hat angerufen","Meine Eltern haben angerufen."],
        ["anschließen","schließt an","schloss an","hat angeschlossen","Lisa hat den Computer angeschlossen."],
        ["ansehen","sieht an","sah an","hat angesehen","Er sieht (sich) das Beispiel an."],
        ["ansprechen","spricht an","sprach an","hat angesprochen","Werbung spricht oft Gefühle an."],
        ["anstehen","steht an","stand an","hat/ist angestanden","Die Leute standen geduldig an."],
        ["anziehen (sich)","zieht an","zog an","hat angezogen","Andreas hat sich die Jacke angezogen. "],
        ["auffallen","fällt auf","fiel auf","ist aufgefallen","Seine Stimme fiel wirklich allen auf."],
        ["aufgeben","gibt auf","gab auf","hat aufgegeben","Er gab bei Problemen nie auf."],
        ["aufhängen","hängt auf","hing auf","hat aufgehängt","Er hängt das Plakat auf."],
        ["aufhalten","hält auf","hielt auf","hat aufgehalten","Keiner kann ihn aufhalten."],
        ["aufladen","lädt auf","lud auf","hat aufgeladen","Sie können den Geldkarten-Chip am Automaten aufladen."],
        ["aufschlagen","schlägt auf","schlug auf","hat aufgeschlagen","Haben Sie das Buch aufgeschlagen?"],
        ["aufschreiben","schreibt auf","schrieb auf","hat aufgeschrieben","Wir haben die Adresse nicht aufgeschrieben."],
        ["aufstehen","steht auf","stand auf","ist aufgestanden","Heute bin ich um 11 Uhr aufgestanden."],
        ["auftreten","tritt auf","trat auf","ist aufgetreten","Der Schauspieler tritt in einem Theaterstück auf."],
        ["aufwachsen","wächst auf","wuchs auf","ist aufgewachsen","Ole ist in Hamburg aufgewachsen."],
        ["(sich) ausdenken","denkt (sich) aus","dachte (sich) aus","hat (sich) ausgedacht","Ich habe mir ein Spiel ausgedacht."],
        ["ausgeben","gibt aus","gab aus","hat ausgegeben","Sie gibt viel für ihre Haustiere aus. "],
        ["ausgehen","geht aus","ging aus","ist ausgegangen","Wir sind gestern noch ausgegangen. "],
        ["ausgleichen","gleicht aus","glich aus","hat ausgeglichen","Schüler können ihre Schwächen ausgleichen."],
        ["aushalten","hält aus","hielt aus","hat ausgehalten","Ich kann den Lärm nicht aushalten."],
        ["(sich) auskennen","kennt (sich) aus","kannte (sich) aus","hat (sich) ausgekannt","Er kannte sich hier gut aus."],
        ["ausladen","lädt aus","lud aus","hat ausgeladen","Er hat die Möbel ausgeladen."],
        ["ausleihen","leiht aus","lieh aus","hat ausgeliehen","Sie hat die Schuhe ausgeliehen."],
        ["ausschlafen","schläft aus","schlief aus","hat ausgeschlafen","In den Ferien habe ich immer ausgeschlafen. "],
        ["aussehen","sieht aus","sah aus","hat ausgesehen","Im Internet hat der Pulli toll ausgesehen. "],
        ["aussprechen","spricht aus","sprach aus","hat ausgesprochen","Wie spricht man das aus?"],
        ["aussteigen","steigt aus","stieg aus","ist ausgestiegen","Wo sind Sie denn ausgestiegen?"],
        ["aussterben","stirbt aus","starb aus","ist ausgestorben","Viele Tiere sind ausgestorben."],
        ["ausziehen","zieht aus","zog aus","ist ausgezogen","Alle haben die Schuhe ausgezogen. "],
        ["ausziehen","zieht aus","zog aus","ist ausgezogen","Sie zogen aus dem Haus aus."],
        ["backen","backt/bäckt","backte","hat gebacken","Wir haben Brot gebacken."],
        ["bedenken","bedenkt","bedachte","hat bedacht","Man muss diesen Punkt auch bedenken."],
        ["(sich) begeben","begibt (sich)","begab (sich)","hat (sich) begeben","Er begibt sich auf Entdeckungsreise "],
        ["beginnen","beginnt","begann","hat begonnen","Das Konzert begann um 22 Uhr."],
        ["behalten","behält","behielt","hat behalten","Sie können das Geld behalten."],
        ["bekommen","bekommt","bekam","hat bekommen","Hast du meine E-Mail bekommen? "],
        ["(sich) benehmen","benimmt (sich)","benahm (sich)","hat (sich) benommen","Er hat sich wie ein Star benommen. "],
        ["beraten","berät","beriet","hat beraten","Eine Freundin hat mich gut beraten. "],
        ["beschließen","beschließt","beschloss","hat beschlossen","Politiker beschlossen, besser zusammenzuarbeiten."],
        ["beschreiben","beschreibt","beschrieb","hat beschrieben","Er hat seine Erfahrungen beschrieben."],
        ["besitzen","besitzt","besaß","hat besessen","Frau Isser besaß allein drei Autos."],
        ["bestehen","besteht","bestand","hat bestanden","Erik hat die Prüfung bestanden."],
        ["betragen","beträgt","betrug","hat betragen","Die Gebühren für das Telefon betragen 2 € am Tag."],
        ["betreiben","betreibt","betrieb","hat betrieben","Sie haben viel Aufwand betrieben."],
        ["betrügen","betrügt","betrog","hat betrogen","Niemand kann nachprüfen ob man bezahlt oder betrügt."],
        ["beweisen","beweist","bewies","hat bewiesen","Er bewies, dass man vieles schaffen kann."],
        [" (sich) bewerben","bewirbt (sich)","bewarb (sich)","hat (sich) beworben","Sie hat sich um die Stelle beworben."],
        ["beziehen","bezieht","bezog","hat bezogen","Worauf beziehen Sie sich?"],
        ["bieten","bietet","bot","hat geboten","Das Hotel hat guten Service geboten."],
        ["binden","bindet","band","hat gebunden","Sie hat einen Schal um den Hals gebunden. "],
        ["bitten","bittet","bat","hat gebeten","Er hat mich um eine Nachricht gebeten."],
        ["bleiben","bleibt","blieb","ist geblieben","Ich bin gestern zu Hause geblieben."],
        ["brechen","bricht","brach","hat gebrochen","Er brach sich beim Unfall ein Bein."],
        ["brennen","brennt","brannte","hat gebrannt","Die Feuerwehr kommt, wenn es brennt."],
        ["bringen","bringt","brachte","hat gebracht","Theresa hat mir einen Tee gebracht."],
        ["denken","denkt","dachte","hat gedacht","Woran hast du gerade gedacht?"],
        ["drankommen","kommt dran","kam dran","ist drangekommen","Wer kommt dran?"],
        ["durcheinandergehen","geht durcheinander","ging durcheinander","ist durcheinandergegangen","In dem Chaos ging alles durcheinander."],
        ["einbringen","bringt ein","brachte ein","hat eingebracht","Schüler bringen ihre Ideen ein."],
        ["einfallen","fällt ein","fiel ein","ist eingefallen","Mir fiel bei der Prüfung nichts ein."],
        ["eingeben","gibt ein","gab ein","hat eingegeben","Geben Sie das Ziel ein!"],
        ["eingehen","geht ein","ging ein","ist eingegangen","Er geht auf das Beispiel ein."],
        ["einhalten","hält ein","hielt ein","hat eingehalten","Ich habe den Zeitplan nicht eingehalten."],
        ["einladen","lädt ein","lud ein","hat eingeladen","Tina hat mich zum Essen eingeladen."],
        ["einnehmen","nimmt ein","nahm ein","hat eingenommen ","Nehmen Sie diese Tabletten ein."],
        ["einreiben","reibt ein","rieb ein","hat eingerieben","Wir haben die Tafel mit Seife eingerieben. "],
        ["einschlafen","schläft ein","schlief ein","ist eingeschlafen","Wann bist du eingeschlafen?"],
        ["einschlagen","schlägt ein","schlug ein","hat eingeschlagen","Er hat diesen Weg eingeschlagen."],
        ["einsteigen","steigt ein","stieg ein","ist eingestiegen","Wo steigen wir ein?"],
        ["eintragen","trägt ein","trug ein","hat eingetragen","Im Ausweis werden Arbeitszeiten eingetragen. "],
        ["einwerfen","wirft ein","warf ein","hat eingeworfen","Man wirft das Geld in die Zeitungskästen ein. "],
        ["einziehen","zieht ein","zog ein","ist eingezogen","Gestern sind die neuen Nachbarn eingezogen. "],
        ["einziehen","zieht ein","zog ein","hat/ist eingezogen","Elisa zieht ein."],
        ["empfangen","empfängt","empfing","hat empfangen","Sie können 30 Programme empfangen. "],
        ["empfehlen","empfiehlt","empfahl","hat empfohlen","Wer hat dir dieses Hotel empfohlen? "],
        ["entlanggehen","geht entlang","ging entlang","ist entlanggegangen","Er ging die Straße entlang."],
        ["entnehmen","entnimmt","entnahm","hat entnommen","Entnehmen Sie bitte den abgehobenen Geldbetrag! "],
        ["(sich) entscheiden","entscheidet (sich)","entschied (sich)","hat (sich) entschieden","Hast du dich für ein Buch entschieden? "],
        ["entsprechen","entspricht","entsprach","hat entsprochen","Was entspricht diesem Wort in ihrer Sprache? "],
        ["entstehen","entsteht","entstand","ist entstanden","Das Gebäude entstand im Jahr 1963. "],
        ["entwerfen","entwirft","entwarf","hat entworfen","Haben Sie das Plakat entworfen?"],
        ["erfahren","erfährt","erfuhr","hat erfahren","Ich erfuhr später, was passiert ist."],
        ["erfinden","erfindet","erfand","hat erfunden","Wer hat das Telefon erfunden?"],
        ["erhalten","erhält","erhielt","hat erhalten","Die Chipkarte erhalten sie an der Rezeption."],
        ["erkennen","erkennt","erkannte","hat erkannt","Hast du ihn erkannt?"],
        ["erraten","errät","erriet","hat erraten","Er hat das Rätsel erraten."],
        ["erscheinen","erscheint","erschien","ist erschienen","Der Roman ist 1986 erschienen."],
        ["erschießen","erschießt","erschoss","hat erschossen","Der Jäger erschießt die das Tier."],
        ["erschließen","erschließt","erschloss","hat erschlossen","Ich habe die Bedeutung über den Kontext erschlossen."],
        ["erschrecken","erschrickt","erschrak","ist erschrocken","Er erschrak, die Tasche war weg."],
        ["essen","isst","aß","hat gegessen","Er hat eine Pizza gegessen."],
        ["fahren","fährt","fuhr","ist gefahren","Bist du im Mai nach Berlin gefahren? "],
        ["fallen","fällt","fiel","ist gefallen","Das Glas ist auf den Boden gefallen. "],
        ["fernsehen","sieht fern","sah fern","hat ferngesehen","Wir haben gestern lang ferngesehen. "],
        ["festnehmen","nimmt fest","nahm fest","hat festgenommen ","Der Täter wurde von der Polizei festgenommen. "],
        ["finden","findet","fand","hat gefunden","Hast du eine Stelle gefunden?"],
        ["fliegen","fliegt","flog","ist geflogen","Ein Vogel ist ins Zimmer geflogen. "],
        ["fliehen","flieht","floh","ist geflohen","Viele Menschen flohen aus der DDR. "],
        ["fressen","frisst","fraß","hat gefressen","Der Fuchs fraß den Käse."],
        ["geben","gibt","gab","hat gegeben","Peter hat mir die DVD gegeben."],
        ["gefallen","gefällt","gefiel","hat gefallen","Was hat ihnen besonders gut gefallen. "],
        ["gehen","geht","ging","ist gegangen","Daniel ist in die Pizzeria gegangen. "],
        ["gelingen","gelingt","gelang","ist gelungen","Das muss man üben, dann gelingt es auch. "],
        ["gelten","gilt","galt","hat gegolten","Unsere Reservierung hat leider nicht gegolten. "],
        ["genießen","genießt","genoss","hat genossen","Wir haben das gute Essen genossen. "],
        ["geraten","gerät","geriet","ist geraten","Ein Handwerker geriet in finanzielle Schwierigkeiten. "],
        ["geschehen","geschieht","geschah","ist geschehen","Was geschieht außerhalb der Wohnung? "],
        ["gewinnen","gewinnt","gewann","hat gewonnen","Heute hat mein Team gewonnen."],
        ["gießen","gießt","goss","hat gegossen","Herr Kirchmair hat unsere Blumen gegossen."],
        ["greifen","greift","griff","hat gegriffen","Er griff nach der Kaffeetasse."],
        ["gutschreiben","schreibt gut","schrieb gut","hat gutgeschrieben","Der Betrag wird ihrem Konto gutgeschrieben"],
        ["halten","hält","hielt","hat gehalten","Was hältst du von der Idee?"],
        ["hängen","hängt","hing","hat gehangen","Der Mantel hing an der Garderobe. "],
        ["heben","hebt","hob","hat gehoben","Sie hat ihre Stimme gehoben."],
        ["heimkommen","kommt heim","kam heim","ist heimgekommen","Sie sind gestern spät heimgekommen."],
        ["heißen","heißt","hieß","hat geheißen","Wie hat der Ort geheißen?"],
        ["helfen","hilft","half","hat geholfen","Danke, dass du mir geholfen hast."],
        ["herankommen","kommt heran","kam heran","ist herangekommen","Man darf nicht näher an die Kunstwerke herankommen."],
        ["herausfinden","findet heraus","fand heraus","hat herausgefunden","Ich konnte nicht herausfinden, wo der Künstler wohnt. "],
        ["herausnehmen","nimmt heraus","nahm heraus","hat herausgenommen","Er hat das Buch aus der Tasche herausgenommen."],
        ["hereinkommen","kommt herein","kam herein","ist hereingekommen","Er kam kurz ins Haus herein."],
        ["herumgehen","geht herum","ging herum","ist herumgegangen","Die Studenten sind im Raum herumgegangen."],
        ["herunterladen","lädt herunter","lud herunter","hat heruntergeladen","Hast du die Musik heruntergeladen?"],
        ["hierherkommen","kommt hierher","kam hierher","ist hierhergekommen","Er ist zum Deutschlernen hierhergekommen."],
        ["hinaufgehen","geht hinauf","ging hinauf","ist hinaufgegangen","Gehen Sie die Treppe hinauf."],
        ["hineingehen","geht hinein","ging hinein","ist hineingegangen","Er geht durch das Tor hinein. "],
        ["hinfahren","fährt hin","fuhr hin","ist hingefahren","Bist du allein hingefahren?"],
        ["hingehen","geht hin","ging hin","ist hingegangen","Wir gehen morgen wieder hin."],
        ["hinsehen","sieht hin","sah hin","hat hingesehen","Sie hat genau hingesehen."],
        ["hinterlassen","hinterlässt","hinterließ","hat hinterlassen","Der Anrufer hat eine Nachricht hinterlassen. "],
        ["hochladen","lädt hoch","lud hoch","hat hochgeladen","Ich habe die Fotos hochgeladen."],
        ["hochziehen","zieht hoch","zog hoch","hat hochgezogen","Er hat die Schulter hochgezogen."],
        ["kennen","kennt","kannte","hat gekannt","Ich habe den Film schon gekannt."],
        ["klarkommen","kommt klar","kam klar","ist klargekommen","Elisa kam nicht mehr mit ihrer Mutter klar. "],
        ["klingen","klingt","klang","hat geklungen","Die Stimme hat freundlich geklungen. "],
        ["kommen","kommt","kam","ist gekommen","Sie ist 2010 nach Deutschland gekommen. "],
        ["laden","lädt","lud","hat geladen","Haben Sie den Akku geladen?"],
        ["lassen","lässt","ließ","hat gelassen","Haben Sie Lücken für Notizen gelassen? "],
        ["laufen","läuft","lief","ist gelaufen","Wir liefen schnell zur Grenze."],
        ["leidtun","tut leid","tat leid","hat leidgetan","Es tat mir wirklich sehr leid."],
        ["leihen","leiht","lieh","hat geliehen","Lia hat mir einen Schirm geliehen. "],
        ["lesen","liest","las","hat gelesen","Hast du das neue Buch von Süskind gelesen? "],
        ["liegen","liegt","lag","hat/ist gelegen","Gestern lag ich zu lange in der Sonne. "],
        ["losfahren","fährt los","fuhr los","ist losgefahren","Vor einer Stunde ist sie losgefahren. "],
        ["losgehen","geht los","ging los","ist losgegangen","Der Kurs ist um 18 Uhr losgegangen. "],
        ["lügen","lügt","log","hat gelogen","Er hat gelogen."],
        ["melken","melkt","melkte","hat gemolken","Sie haben die Kühe gemolken."],
        ["messen","misst","maß","hat gemessen","Du brauchst kein Fieber zu messen. "],
        ["mitbringen","bringt mit","brachte mit","hat mitgebracht","Sie hat einen Kuchen mitgebracht."],
        ["mithelfen","hilft mit","half mit","hat mitgeholfen","Alle haben mitgeholfen."],
        ["mitkommen","kommt mit","kam mit","ist mitgekommen","Alle Freunde sind mitgekommen."],
        ["mitlesen","liest mit","las mit","hat mitgelesen","Lesen Sie mit."],
        ["mitnehmen","nimmt mit","nahm mit","hat mitgenommen","Ich nehme immer ein Buch mit."],
        ["mitsingen","singt mit","sang mit","hat mitgesungen","Einige haben laut mitgesungen."],
        ["mögen","mag","mochte","hat gemocht","Das Kind hat den Saft nicht gemocht. "],
        ["nachdenken","denkt nach","dachte nach","hat nachgedacht","Sie denken über das Konzept nach. "],
        ["nachgeben","gibt nach","gab nach","hat nachgegeben","Mal muss der eine nachgeben, mal der andere. "],
        ["nehmen","nimmt","nahm","hat genommen","Sie hat die Tabletten nicht genommen. "],
        ["nennen","nennt","nannte","hat genannt","Sie hat ihm die Adresse genannt."],
        ["raten","rät","riet","hat geraten","Ich habe ihren Namen geraten."],
        ["rausgehen","geht raus","ging raus","ist rausgegangen","Ich war krank und bin nicht rausgegangen. "],
        ["reiten","reitet","ritt","ist geritten","Früher ist sie viel auf ihrem Pferd geritten. "],
        ["rennen","rennt","rannte","ist gerannt","Wir rannten zur Grenze."],
        ["riechen","riecht","roch","hat gerochen","Die Rosen haben gut gerochen."],
        ["rufen","ruft","rief","hat gerufen","Hast du mich gerufen?"],
        ["scheinen","scheint","schien","hat geschienen","Die Sonne hat den ganzen Tag geschienen. "],
        ["schiefgehen","geht schief","ging schief","ist schiefgegangen","Das ist richtig schiefgegangen, leider!"],
        ["schießen","schießt","schoss","hat geschossen","Er hat ein Tor geschossen."],
        ["schlafen","schläft","schlief","hat geschlafen","Ich habe nur drei Stunden geschlafen. "],
        ["schlagen","schlägt","schlug","hat geschlagen","Sein Herz schlug ganz schnell."],
        ["schließen","schließt","schloss","hat geschlossen","Er schließt das Geschäft um 19 Uhr. "],
        ["schmelzen","schmilzt","schmolz","ist geschmolzen","Das Eis ist in der Sonne geschmolzen. "],
        ["schneiden","schneidet","schnitt","hat geschnitten","Ich habe das Gemüse geschnitten."],
        ["schreiben","schreibt","schrieb","hat geschrieben","Er hat eine Mail an Sarah geschrieben. "],
        ["schweigen","schweigt","schwieg","hat geschwiegen","Alle schweigen, wenn der Chef kommt. "],
        ["schwimmen","schwimmen","schwamm","hat/ist geschwommen","Sie schwamm am schnellsten."],
        ["sehen","sieht","sah","hat gesehen","Hast du den Film schon gesehen?"],
        ["singen","singt","sang","hat gesungen","Ben hat schon immer gern gesungen."],
        ["sinken","sinkt","sank","ist gesunken","Der Puls sinkt, wenn man langsame Musik hört. "],
        ["sitzen","sitzt","saß","hat/ist gesessen","Und dann saßen sie lang im Café."],
        ["sprechen","spricht","sprach","hat gesprochen","Ich habe heute mit ihr gesprochen."],
        ["springen","springt","sprang","ist gesprungen","Ich bin schon mal Fallschirm gesprungen."],
        ["stattfinden","findet statt","fand statt","hat stattgefunden","Das Konzert hat nicht stattgefunden. "],
        ["stechen","sticht","stach","hat gestochen","Jemand verschluckt eine Biene und wird im Hals gestochen. "],
        ["stehen","steht","stand","hat/ist gestanden","Er stand lange vor der Tür."],
        ["stehlen","stiehlt","stahl","hat gestohlen","Ein Rabe hat einen Käse gestohlen."],
        ["steigen","steigt","stieg","ist gestiegen","Die Temperatur ist stark gestiegen. "],
        ["sterben","stirbt","starb","ist gestorben","Der Autofahrer ist bei dem Unfall nicht gestorben. "],
        ["stinken","stinkt","stank","hat gestunken","Der Müll hat schrecklich gestunken. "],
        ["streiten","streitet","stritt","hat gestritten","Warum habt ihr euch schon wieder gestritten. "],
        ["teilnehmen","nimmt teil","nahm teil","hat teilgenommen","Sie hat ein einem Training teilgenommen. "],
        ["tragen","trägt","trug","hat getragen","Sie hat die schwere Tasche allein getragen. "],
        ["treffen","trifft","traf","hat getroffen","Maria hat gestern ihre Freunde getroffen. "],
        ["trinken","trinkt","trank","hat getrunken","Hast du mit Daniel Kaffee getrunken? "],
        ["tun","tut","tat","hat getan","Was kann ich für sie tun?"],
        ["übernehmen","übernimmt","übernahm","hat übernommen","Er hat die Firma von seinen Eltern übernommen. "],
        ["übersehen","übersieht","übersah","hat übersehen","Ein Autofahrer übersah die Trambahn. "],
        ["überweisen","überweist","überwies","hat überwiesen","Ich habe das Geld auf dein Konto überwiesen. "],
        ["überwinden","überwindet","überwand","hat überwunden","Mit viel Energie hat er alle Probleme überwunden. "],
        ["umsehen (sich)","sieht um","sah um","hat umgesehen","Wir haben uns umgesehen."],
        ["umsteigen","steigt um","stieg um","ist umgestiegen","Wir sind einmal umgestiegen."],
        ["umziehen","zieht um","zog um","ist umgezogen","Letzte Woche sind wir umgezogen. "],
        ["(sich) unterhalten","unterhält (sich)","unterhielt (sich)","hat (sich) unterhalten","Wir haben uns lange unterhalten."],
        ["unternehmen","unternimmt","unternahm","hat unternommen","Wir haben im Urlaub viel unternommen. "],
        ["(sich) unterscheiden","unterscheidet (sich)","unterschied (sich)","hat (sich) unterschieden","Sie hat sich von den anderen unterschieden. "],
        ["unterschreiben","unterschreibt","unterschrieb","hat unterschrieben","Hast du den Vertrag unterschrieben. "],
        ["unterstreichen","unterstreicht","unterstrich","hat unterstrichen","Unterstreichen Sie die Verben."],
        ["verbinden","verbindet","verband","hat verbunden","Er hat mich mit dem Chef verbunden."],
        ["verbringen","verbringt","verbrachte","hat verbracht","Sie haben zu viel Zeit im Internet verbracht."],
        ["vergehen","vergeht","verging","ist vergangen","Der Urlaub ist so schnell vergangen."],
        ["vergessen","vergisst","vergaß","hat vergessen","Hast du vergessen, mich anzurufen?"],
        ["vergleichen","vergleicht","verglich","hat verglichen","Sie hat die Handys genau verglichen."],
        ["vergraben","vergräbt","vergrub","hat vergraben","Sie haben die Blumenzwiebeln vergraben."],
        ["verhalten (sich)","verhält","verhielt","hat verhalten","Er hat sich nicht richtig verhalten."],
        ["verlaufen","verläuft","verlief","ist verlaufen","Das Gespräch ist gut verlaufen."],
        ["verlieren","verliert","verlor","hat verloren","Ich habe mein Handy verloren."],
        ["vermeiden","vermeidet","vermied","hat vermieden","Er konnte das leider nicht vermeiden."],
        ["vernehmen","vernimmt","vernahm","hat vernommen","Die Zeugen wurden vernommen."],
        ["verraten","verrät","verriet","hat verraten","Sie haben die Überraschung verraten."],
        ["verschieben","verschiebt","verschob","hat verschoben","Sie haben die Prüfung auf Dienstag verschoben."],
        ["verschlafen","verschläft","verschlief","hat verschlafen","Entschuldigung, ich habe verschlafen."],
        ["verschreiben","verschreibt","verschrieb","hat verschrieben","Der Arzt verschreibt ihnen ein Medikament. "],
        ["verschwinden","verschwindet","verschwand","ist verschwunden","Er ist verschwunden!"],
        ["versprechen","verspricht","versprach","hat versprochen","Er versprach, dass er gut aufpasst."],
        ["verstehen","versteht","verstand","hat verstanden","Ich habe die Frage nicht verstanden."],
        ["verzeihen","verzeiht","verzieh","hat verziehen","Verzeihen Sie bitte!"],
        ["vorbeifliegen","fliegt vorbei","flog vorbei","ist vorbeigeflogen","Ein Vogel fliegt vorbei."],
        ["vorbeigehen","geht vorbei","ging vorbei","ist vorbeigegangen","Sie geht am Kinderspielplatz vorbei."],
        ["vorbeikommen","kommt vorbei","kam vorbei","ist vorbeigekommen","Er kam persönlich vorbei."],
        ["vorgehen","geht vor","ging vor","ist vorgegangen","Ich gehe nicht zum Fußball, unser Hochzeitstag geht vor."],
        ["vorkommen","kommt vor","kam vor","ist vorgekommen","Das Problem kam mehrmals vor."],
        ["vorlesen","liest vor","las vor","hat vorgelesen","Er las den Text vor."],
        ["(sich) vornehmen","nimmt (sich) vor","nahm (sich) vor","hat (sich) vorgenommen","Er hat sich viel vorgenommen."],
        ["vorschlagen","schlägt vor","schlug vor","hat vorgeschlagen","Wer hat dieses Restaurant vorgeschlagen?"],
        ["vorsingen","singt vor","sang vor","hat vorgesungen","Der Rabe sang dem Fuchs ein Lied vor."],
        ["vortragen","trägt vor","trug vor","hat vorgetragen","Er hat ein Referat vorgetragen."],
        ["wachsen","wächst","wuchs","ist gewachsen","Das Gras ist sehr schnell gewachsen."],
        ["waschen","wäscht","wusch","hat gewaschen","Er hat das Gemüse gewaschen."],
        ["wegfahren","fährt weg","fuhr weg","ist weggefahren","Meine Freundin ist gestern weggefahren."],
        ["weggehen","geht weg","ging weg","ist weggegangen","Sie ist mit ihren Freunden weggegangen."],
        ["weglassen","lässt weg","ließ weg","hat weggelassen","Dieses Wort kann man weglassen."],
        ["wegwerfen","wirft weg","warf weg","hat weggeworfen","Lebensmittel werden oft weggeworfen."],
        ["wegziehen","zieht weg","zog weg","ist weggezogen","Sie ist wegen der Arbeit weggezogen."],
        ["wehtun","tut weh","tat weh","hat wehgetan","Mein Knie tat weh."],
        ["weitergeben","gibt weiter","gab weiter","hat weitergegeben","Hast du das Blatt weitergegeben."],
        ["weiterhelfen","hilft weiter","half weiter","hat weitergeholfen","Die Zentrale hat mir weitergeholfen."],
        ["weiterlesen","liest weiter","las weiter","hat weitergelesen","Er hat den Text weitergelesen."],
        ["weiterschreiben","schreibt weiter","schrieb weiter","hat weitergeschrieben","Wir haben das Lied weitergeschrieben. "],
        ["werben","wirbt","warb","hat geworben","Die Firma hat nur mit ihrem Namen geworben."],
        ["werden","wird","wurde","ist geworden","Sofia ist gestern dreißig geworden."],
        ["werfen","wirft","warf","hat geworfen","Wir haben einfach eine Münze geworfen."],
        ["widersprechen","widerspricht","widersprach","hat widersprochen","Ich habe ihm nicht widersprochen. "],
        ["wiederbekommen","bekommt wieder","bekam wieder","hat wiederbekommen","Er hat seine Tasche wiederbekommen."],
        ["wiederfinden","findet wieder","fand wieder","hat wiedergefunden","Ich habe die Karte wiedergefunden."],
        ["wissen","weiß","wusste","hat gewusst","Leider habe ich das nicht gewusst."],
        ["zerreißen","zerreißt","zerriss","hat zerrissen","Er zerreißt sein altes T-Shirt."],
        ["ziehen","zieht","zog","hat gezogen","Sie ist zu ihrem Freund gezogen."],
        ["zugehen","geht zu","ging zu","ist zugegangen","Hier geht es im Unterricht anders zu, als an normalen Schulen. "],
        ["zunehmen","nimmt zu","nahm zu","hat zugenommen","Teamarbeit hat in letzter Zeit zugenommen."],
        ["zurechtkommen","kommt zurecht","kam zurecht","ist zurechtgekommen","Er ist mit der Situation nicht zurechtgekommen."],
        ["zurückerhalten","erhält zurück","erhielt zurück","hat zurückerhalten","Die eingezogene Karte erhalten Sie in der Bank zurück."],
        ["zurückgehen","geht zurück","ging zurück","ist zurückgegangen","Er ist nach Deutschland zurückgegangen."],
        ["zurückkommen","kommt zurück","kam zurück","ist zurückgekommen","Sie ist aus Südamerika zurückgekommen."],
        ["zurückrufen","ruft zurück","rief zurück","hat zurückgerufen","Herr Jeschke hat nicht zurückgerufen. "],
        ["zusammenbleiben","bleibt zusammen","blieb zusammen","ist zusammengeblieben","Wir sind froh, dass wir zusammengeblieben."],
        ["zusammenbrechen","bricht zusammen","brach zusammen","ist zusammengebrochen","Der Bär brach kraftlos zusammen."],
        ["zusammentreffen","trifft zusammen","traf zusammen","ist zusammengetroffen","Wirklichkeit und Phantasie sind zusammengetroffen."],
        ["zusammenziehen","zieht zusammen","zog zusammen","ist zusammengezogen","Carla und Alex sind zusammengezogen."],
        ["zuwenden","wendet zu","wandte zu","hat zugewandt","Wende das Gesicht der Sonne zu!"],
        ["zwingen","zwingt","zwang","hat gezwungen","Die finanzielle Situation zwang sie zu sparen."]
    ]
}
